#pragma once

#define SAMPLE_FREQUENCY   16000
#define SAMPLE_BIT_WIDTH   16
#define BYTES_PER_SAMPLE   sizeof(int16_t)
#define NUMBER_OF_CHANNELS 2

// F/50 = 20 ms
#define SAMPLES_PER_BLOCK      ((SAMPLE_FREQUENCY / 50) * NUMBER_OF_CHANNELS)
#define SAMPLES_PER_BLOCK_OPUS ((SAMPLE_FREQUENCY / 50) * NUMBER_OF_CHANNELS)
#define INITIAL_BLOCKS         10
#define TIMEOUT                1000

#define BLOCK_SIZE      (BYTES_PER_SAMPLE * SAMPLES_PER_BLOCK)
#define BLOCK_SIZE_OPUS (BYTES_PER_SAMPLE * SAMPLES_PER_BLOCK_OPUS)
#define BLOCK_COUNT     (INITIAL_BLOCKS)

// Holds 1ms of audio data
#define USB_BLOCK_SIZE (SAMPLE_FREQUENCY / 1000 * NUMBER_OF_CHANNELS * BYTES_PER_SAMPLE)
